### ISSUE TITLE
doc/tutorial?

### ISSUE THREAD

**Issue by tshirtman** [garyjohnson/kvaut#1]
Hey, this seems nice, but is there any doc about how to use it?

Thanks :)

**Comment by garyjohnson** [comment]
Documentation is coming very soon. If you wanted to get started before that the usage / api surface will be similar to pqaut. You can also look at the tests and test apps under the test_apps folder.

**Comment by garyjohnson** [comment]
Got documentation kicked off here: https://github.com/garyjohnson/kvaut/commit/d15ae45ccb705083a63a8b363e15416bba960138 
I'll keep adding more but if there's anything you want to see in particular add a comment.

**Comment by tshirtman** [comment]
:+1:
